# use https://github.com/linuxserver/docker-code-server

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0 # root (common user:1000)
      - PGID=0 # root (common user:1000)
      - TZ=Asia/Tokyo
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
      - ./:/container
    ports:
      - 8443:8443
    restart: unless-stopped